messages:
  skill_activated: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fСкилл §x§0§0§E§9§1§9а§x§0§0§E§B§2§8к§x§0§0§E§D§3§6т§x§0§0§F§0§4§5и§x§0§0§F§2§5§4в§x§0§0§F§4§6§3и§x§0§0§F§6§7§1р§x§0§0§F§8§8§0о§x§0§0§F§B§8§Fв§x§0§0§F§D§9§Dа§x§0§0§F§F§A§Cн."
  skill_already_active: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &cУ вас уже §x§0§0§E§9§1§9а§x§0§0§E§B§2§8к§x§0§0§E§D§3§6т§x§0§0§F§0§4§5и§x§0§0§F§2§5§4в§x§0§0§F§4§6§3и§x§0§0§F§6§7§1р§x§0§0§F§8§8§0о§x§0§0§F§B§8§Fв§x§0§0§F§D§9§Dа§x§0§0§F§F§A§Cн&F скилл. &7(/skills)"
  skills_disabled: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВсе скиллы §x§F§B§0§8§0§8о§x§F§3§0§C§0§Cт§x§E§A§1§0§1§0к§x§E§2§1§4§1§4л§x§D§9§1§8§1§8ю§x§D§1§1§B§1§Bч§x§C§8§1§F§1§Fе§x§C§0§2§3§2§3н§x§B§7§2§7§2§7ы&f."
  skill_on_cooldown: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fСкилл на §x§0§0§E§9§1§9п§x§0§0§E§B§2§8е§x§0§0§E§D§3§6р§x§0§0§F§0§4§5е§x§0§0§F§2§5§4з§x§0§0§F§4§6§3а§x§0§0§F§6§7§1р§x§0§0§F§8§8§0я§x§0§0§F§B§8§Fд§x§0§0§F§D§9§Dк§x§0§0§F§F§A§Cе&f."
  unknown_skill: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fНеизвестный скилл."
  glow_activated: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВокруг вас собралась §x§F§B§0§8§0§8а§x§E§A§1§0§1§0у§x§D§9§1§8§1§8р§x§C§8§1§F§1§Fа§x§B§7§2§7§2§7!"
  glow_removed: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &7Эффект ауры прошёл."
  thunder_hit: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы ударили §x§E§9§B§D§0§0{targetName}&f молнией!"
  no_players_nearby: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fИгроков в пределах &7{radius}&f блоков не найдено."
  ice_skill_activated: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fПУСК!"
  frozen: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы были §x§0§0§1§C§F§Fз§x§0§0§2§9§F§Fа§x§0§0§3§7§F§Fм§x§0§0§4§4§F§Fо§x§0§0§5§2§F§Fр§x§0§0§5§F§F§Fо§x§0§0§6§C§F§Fж§x§0§0§7§A§F§Fе§x§0§0§8§7§F§Fн§x§0§0§9§5§F§Fы§x§0§0§A§2§F§F!"
  thawed: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы были §x§0§0§1§C§F§Fр§x§0§0§2§8§F§Fа§x§0§0§3§4§F§Fз§x§0§0§4§1§F§Fм§x§0§0§4§D§F§Fо§x§0§0§5§9§F§Fр§x§0§0§6§5§F§Fо§x§0§0§7§1§F§Fж§x§0§0§7§D§F§Fе§x§0§0§8§A§F§Fн§x§0§0§9§6§F§Fы§x§0§0§A§2§F§F!"
  healed: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы были вылечены на {healAmount} сердец!"
  knocked_back: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы оттолкнули §x§0§3§F§F§0§0{targetName}!"
  berserk_activated: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы активировали режим §x§F§F§0§0§0§0Б§x§F§F§0§0§0§8е§x§F§E§0§1§1§0р§x§F§E§0§1§1§8с§x§F§E§0§1§2§0е§x§F§D§0§1§2§7р§x§F§D§0§2§2§Fк§x§F§C§0§2§3§7а§x§F§C§0§2§3§F!"

skills:
  thunder:
    damage: 13
    actionbarname: "§6§l❖ §fДействующий скил: §eМолниеносец§f §6§l❖"
    color: "#FFFF00"  # Желтый цвет
  ice:
    actionbarname: "§6§l❖ §fДействующий скил: §bАйсберг§f §6§l❖"
    freeze_time: 5
    color: "#1800FF"  # Желтый цвет
  heal:
    actionbarname: "§6§l❖ §fДействующий скил: §dЛекарь§f §6§l❖"
    heal_amount: 4
    color: "#FF00B0"  # Желтый цвет
  knockback:
    actionbarname: "§6§l❖ §fДействующий скил: §aВышибала§f §6§l❖"
    distance: 10
    color: "#38B823"  # Желтый цвет
  berserk:
    actionbarname: "§6§l❖ §fДействующий скил: §4Берсерк§f §6§l❖"
    color: "#FF0000"  # Желтый цвет
    strength_level: 7
    strength_duration: 5
    slowness_level: 3
    slowness_duration: 10
cooldowns:
  thunder: 10
  ice: 10
  heal: 10
  knockback: 10
  berserk: 10
disabled_worlds:
  - spawn
  - arena
skills_disabled_in_world: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы &cне можете использовать&f навыки в этом мире."
skill_not_allowed_in_mode: "§x§F§F§9§B§0§0§lᴛ§x§F§F§A§B§0§0§lᴏ§x§F§F§B§A§0§0§lᴏ§x§F§F§C§A§0§0§lʟ§x§F§F§D§9§0§0§lᴄ§x§F§F§C§4§0§0§lᴜ§x§F§F§B§0§0§0§lʙ§x§F§F§9§B§0§0§lᴇ
      &8› &fВы &cне можете использовать&f навыки в годе или флае."
