name: SoSkills
main: so.max1soft.skills.Main
version: 1.5
author: somax1soft
description: "t.me/max1soft - Разработчик/ t.me/troyanh - идея (CMI)"
api-version: 1.16
depend:
  - CMI

commands:
  soskills:
    description: Управление скиллами.
    usage: /soskills <activate|disable> [название]
    aliases: [skills]
